input EditAggregateInput {
  id: ID!
  title: String
}

type EditAggregateResponse {
  trackable: Aggregate!
}

extend type Mutation {
  editAggregate(aggregate: EditAggregateInput!): EditAggregateResponse!
}
