type UnaggregateTrackableResponse {
  removedAggregateId: ID
  aggregate: Aggregate
  trackable: ITrackable!
}

extend type Mutation {
  unaggregateTrackable(id: ID!): UnaggregateTrackableResponse!
}
